services:
  tour-sales:
    build:
      context: /tour-sales
      dockerfile: /Dockerfile
    container_name: tour-sales
    ports:
      - 8080:8080
    networks:
      backend:
    depends_on:
      database:
        condition: service_healthy


  database:
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: tour_sales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BestPassword
    ports:
      - :5432
    networks:
      backend:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  backend:


volumes:
  database-data: